default: &default
  adapter: postgresql
  encoding: unicode
  username: vakar
  password: 1408
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: rails_book_development

test:
  <<: *default
  database: rails_book_test

production:
  <<: *default
  database: rails_book_production
